steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    dir: 'crud-service'
    args:
      - 'run'
      - 'deploy'
      - 'crud-service'
      - '--source=.'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--project=$PROJECT_ID'
    id: 'deploy-crud-service'

options:
  logging: CLOUD_LOGGING_ONLY
