steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'genai-service'
      - '--source=.'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--project=$PROJECT_ID'
      - '--function=genai'
      - '--base-image=nodejs22'
    id: 'deploy-genai-service'

options:
  logging: CLOUD_LOGGING_ONLY
